const translations = {
    en: {
        pageTitle: "Italian Brainrot: Ultimate Merge Fella - Play Online",
        metaDescription: "Play Italian Brainrot: Ultimate Merge Fella online! A hilarious NO ADS mobile game with addictive merging mechanics and wild Italian meme vibes. Fuse fellas, spawn monsters, and conquer this epic game.",
        gameTitle: "Italian Brainrot",
        playNowTitle: "Play Italian Brainrot Now!",
        mainHeading: "About: Ultimate Merge Fella",
        introPara1: "This unique game, Italian Brainrot, fuses addictive merging mechanics with the hilarious vibes of the Italian Brainrot meme scene. Prepare yourself for an exciting journey! Unleash your creativity and spawn some seriously wild monsters by fusing various \"fellas\".",
        introPara2: "Bringing together the chaotic gameplay with a fresh dose of spaghetti-fueled madness, over-the-top Italian stereotypes, and wild characters is the \"Italian Brainrot\" theme. Get ready for a fun and hilarious gaming adventure where you'll be laughing hard at the crazy results of your character fusions.",
        videoTitle: "Gameplay Video",
        howToPlayTitle: "How to Play: Welcome to the Chaotic World!",
        rule1: "<strong>The Goal:</strong> Create badass new characters by using the merge mechanic on two similar dudes (fellas).",
        rule2: "<strong>Get Started:</strong> You'll kick things off with some basic characters on your roster.",
        rule3: "<strong>Mix & Match:</strong> Drop characters to discover a ton of bizarre monsters. It's like a puzzle where you score epic matches to create new fusions.",
        rule4: "<strong>The Quest:</strong> Chasing down epic or rare characters (like the massive capybara from the lore!) is a key quest. Level up your squad or aim to unlock specific unique ones.",
        relatedGamesTitle: "Related Games",
        viewGameButton: "Play Game",
        faqTitle: "Frequently Asked Questions (FAQ)",
        footerText: "&copy; 2025 Italian Brainrot Game Page. Game concept by its respective creators."
    },
    zh: {
        pageTitle: "意大利式.：终极融合伙伴 - 在线玩",
        metaDescription: "在线玩《意大利式.：终极融合伙伴》！这是一款搞笑的“无广告”游戏，融合了令人上瘾的合并机制和疯狂的意大利梗氛围。融合伙伴，生成怪物，征服这款史诗般的游戏。",
        gameTitle: "意大利式.",
        playNowTitle: "立即开玩意大利式.！",
        mainHeading: "关于：终极融合伙伴",
        introPara1: "这款独特的游戏《意大利式.》将令人上瘾的合并机制与意大利式.梗场景的搞笑氛围融为一体。准备好开始一场激动人心的旅程吧！通过融合各种“伙伴”来释放您的创造力并生成一些非常狂野的怪物。",
        introPara2: "将混乱的游戏玩法与新鲜的意面驱动的疯狂、夸张的意大利刻板印象和狂野的角色结合在一起，这就是“意大利式.”的主题。准备好迎接一个充满乐趣和欢笑的游戏冒险，您会为角色融合的疯狂结果而捧腹大笑。",
        videoTitle: "游戏玩法视频",
        howToPlayTitle: "游戏玩法：欢迎来到混乱世界！",
        rule1: "<strong>目标：</strong> 通过对两个相似的家伙（伙伴）使用合并机制来创造超酷的新角色。",
        rule2: "<strong>开始：</strong> 您将从角色名册上的一些基本角色开始。",
        rule3: "<strong>混合搭配：</strong> 投下角色以发现大量奇异的怪物。这就像一个谜题，您需要完成史诗般的匹配来创造新的融合体。",
        rule4: "<strong>任务：</strong> 追捕那些史诗级或稀有角色（比如传说中提到的大型水豚！）是一项关键任务。升级您的小队，或旨在解锁特定的独特角色。",
        relatedGamesTitle: "相关游戏",
        viewGameButton: "开始游戏",
        faqTitle: "常见问题解答 (FAQ)",
        footerText: "&copy; 2025 意大利式.游戏页面。游戏概念归各自创作者所有。"
    },
    es: { // Placeholder for Spanish
        pageTitle: "Italian Brainrot: Ultimate Merge Fella - Juega Online",
        metaDescription: "¡Juega Italian Brainrot: Ultimate Merge Fella online! Un divertidísimo juego SIN ANUNCIOS con mecánicas de fusión adictivas y las locas vibras de los memes de Italian Brainrot.",
        gameTitle: "Italian Brainrot",
        playNowTitle: "¡Juega a Italian Brainrot Ahora!",
        mainHeading: "Acerca de: Ultimate Merge Fella",
        introPara1: "Este juego único, Italian Brainrot, fusiona mecánicas adictivas con las divertidas vibras de la escena de memes de Italian Brainrot. ¡Prepárate para un viaje emocionante!",
        introPara2: "El tema 'Italian Brainrot' une una jugabilidad caótica con una dosis fresca de locura alimentada por espaguetis y personajes salvajes.",
        videoTitle: "Video de Jugabilidad",
        howToPlayTitle: "Cómo Jugar: ¡Bienvenido al Mundo Caótico!",
        rule1: "<strong>El Objetivo:</strong> Crea nuevos personajes fusionando dos tipos similares.",
        rule2: "<strong>Para Empezar:</strong> Comenzarás con algunos personajes básicos en tu lista.",
        rule3: "<strong>Mezcla y Combina:</strong> Suelta personajes para descubrir monstruos extraños.",
        rule4: "<strong>La Misión:</strong> Perseguir personajes raros (¡como el capibara masivo!) es una misión clave.",
        relatedGamesTitle: "Juegos Relacionados",
        viewGameButton: "Jugar",
        faqTitle: "Preguntas Frecuentes (FAQ)",
        footerText: "&copy; 2025 Página del Juego Italian Brainrot. Concepto del juego por sus respectivos creadores."
    }
};
